export const WS_CONNECTION_START = 'WS_CONNECTION_START'
export const WS_CONNECTION_CLOSE = 'WS_CONNECTION_CLOSE'
export const WS_CONNECTION_START_AUTH = 'WS_CONNECTION_START_AUTH'
export const WS_CONNECTION_CLOSE_AUTH = 'WS_CONNECTION_CLOSE_AUTH'
export const WS_SEND_MESSAGE_AUTH = 'WS_SEND_MESSAGE_AUTH'

